/**
 * MATDEV QR Code Plugin
 * Generate QR codes from text or URLs
 */

const QRCode = require('qrcode');
const config = require('../config');
const fs = require('fs-extra');
const path = require('path');

class QRPlugin {
    constructor() {
        this.name = 'qr';
        this.description = 'QR code generation';
        this.version = '1.0.0';
    }

    /**
     * Initialize plugin
     */
    async init(bot) {
        this.bot = bot;
        this.registerCommands();
        console.log('✅ QR plugin loaded');
    }

    /**
     * Register QR commands
     */
    registerCommands() {
        this.bot.messageHandler.registerCommand('qr', this.generateQR.bind(this), {
            description: 'Generate QR code from text or URL',
            usage: `${config.PREFIX}qr <text/url>`,
            category: 'utility',
            plugin: 'qr',
            source: 'qr.js'
        });
    }

    /**
     * Generate QR code command
     */
    async generateQR(messageInfo) {
        try {
            const { args } = messageInfo;
            
            if (!args || args.length === 0) {
                await this.bot.messageHandler.reply(messageInfo, `❌ Please provide text or URL to generate QR code\n\nUsage: ${config.PREFIX}qr <text/url>\n\nExample: ${config.PREFIX}qr https://github.com`);
                return;
            }

            const inputText = args.join(' ');
            
            // Generate QR code as buffer
            const qrOptions = {
                errorCorrectionLevel: 'M',
                width: 256,
                margin: 2,
                color: {
                    dark: '#000000',
                    light: '#FFFFFF'
                }
            };

            const qrBuffer = await QRCode.toBuffer(inputText, qrOptions);

            // Create simple caption
            const caption = `_🔧 Generated by: ${config.BOT_NAME}_`;

            // Send QR code image
            await this.bot.sock.sendMessage(messageInfo.chat_jid, {
                image: qrBuffer,
                caption: caption
            });

        } catch (error) {
            console.error('Error generating QR code:', error);
            await this.bot.messageHandler.reply(messageInfo, '❌ Failed to generate QR code. Please try again.');
        }
    }
}

module.exports = new QRPlugin();